-- qn.13 slice 10a (spec D7): a push subscription records WHOSE it is.
--
-- 0011's index comment states the read this changes: *"Reads are 'every live subscription', which is
-- what a send does."* That was correct while quince had one principal — everyone and the admin were
-- the same set. A device-scoped credential makes them different, and a subscription created by a
-- scoped holder would otherwise receive every device's notifications: the household's backups, their
-- failures, and the device names in the titles.
--
-- NULL MEANS THE ADMIN, the fifth such default in this rung and true of every row that exists — no
-- subscription can have been created by a scoped principal, because none can exist yet.
--
-- FILTERED AT SEND, and read rather than acted on at write time — but placement alone does NOT
-- make revocation take effect, which slice 10a first claimed (quince#1403 review). This column is
-- frozen at INSERT. What send-time placement buys is that a change to the ROW lands on the next
-- send rather than needing the phone to re-subscribe. REVOCATION reaches these rows directly:
-- removing a device's last credential deletes its subscriptions (quince#1366's shape, moved to push).
--
-- SCOPE_UDID RATHER THAN A CREDENTIAL ID, deliberately. A subscription outlives the credential that
-- created it — the phone keeps its endpoint across a re-enrolment — so keying on the credential
-- would silence a device the moment its passkey was reissued. What must be stable here is WHICH
-- DEVICE the holder is confined to, not which key proved it.
ALTER TABLE push_subscriptions ADD COLUMN scope_udid TEXT;
