# golangci-lint config (v2 schema). Pinned version: versions.env (GOLANGCI_LINT_VERSION).
# Conservative, low-friction set — the daemon's value is reliability, so the vet-class
# linters earn their keep; style noise is kept off. gofmt is checked separately in the
# gate; in v2 it's a formatter, and gosimple is folded into staticcheck.
version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - bodyclose

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
